name: Bug Report
description: Report a bug to help us improve
title: "Bug: "
projects:
    - "MrAnyx/8"

body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report! Before creating this report, make sure there isn't already an issue created.

    - type: textarea
      id: bug-description
      attributes:
          label: Bug Description
          description: "Please describe the bug in detail. What happened, and what were you expecting to happen?"
          placeholder: "Explain the bug here..."
      validations:
          required: true

    - type: textarea
      id: reproduction-steps
      attributes:
          label: Reproduction Steps
          description: "How do you trigger this bug? Please walk us through it step by step."
          placeholder: |
              - Go to '...'
              - Click on '....'
              - Scroll down to '....'
              - See error

    - type: textarea
      id: expected-behavior
      attributes:
          label: Expected Behavior
          description: "What did you expect to happen when performing the steps above?"
          placeholder: "Describe the expected behavior..."

    - type: textarea
      id: actual-behavior
      attributes:
          label: Actual Behavior
          description: "What actually happened when performing the steps above?"
          placeholder: "Describe the actual behavior..."

    - type: textarea
      id: logs
      attributes:
          label: Relevant log output
          description: |
              Links? References? Logs? Anything that will give us more context about the issue you are encountering!

              Tip: You can attach images or log files by clicking this area to highlight it and
          render: shell

    - type: checkboxes
      id: bug-report-checklist
      attributes:
          label: Checklist
          description: "Please check the following before submitting your bug report:"
          options:
              - label: "I have searched for existing bug reports and confirmed that this is not a duplicate."
                required: true
              - label: "I have read and understood the project's contribution guidelines."
                required: true
              - label: I agree to follow this project's Code of Conduct
                required: true
