name: Feature request
description: Suggest an idea for this project
title: "Feat: "
projects:
    - "MrAnyx/8"

body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this feature request! Before creating this issue, make sure there isn't already an issue created.

    - type: textarea
      id: feature-description
      attributes:
          label: Feature Description
          description: "Please describe the new feature in detail. What problem does it solve?"
          placeholder: "Explain the feature here..."
      validations:
          required: true

    - type: textarea
      id: additional-context
      attributes:
          label: Additional Context
          description: "Add any additional context, screenshots, or examples that can help clarify your feature request."
          placeholder: "Include any additional context..."
      validations:
          required: false

    - type: checkboxes
      id: feature-request-checklist
      attributes:
          label: Checklist
          description: "Please check the following before submitting your feature request:"
          options:
              - label: "I have searched for existing feature requests and confirmed that this is not a duplicate."
                required: true
              - label: "I have read and understood the project's contribution guidelines."
                required: true
              - label: I agree to follow this project's Code of Conduct
                required: true
